# Site settings
title: Vera Ruel-Wunsch
email: vera.ruelwunsch@gmail.com
description: >
  Vera Ruel-Wunsch is a Product Manager.
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: verathegrouch
github_username:  verarw

# Build settings
markdown: kramdown
